image: gradle:7.4.2-jdk11-alpine

cache:
    paths:
        - .gradle/wrapper
        - .gradle/caches

stages:
    - compile
    - build
    - build_docker_images
    - test

############ compile ##############
compile-TourGuide:
    stage: compile
    script:
        - cd TourGuideApp
        - gradle compileJava assemble

compile-GpsUtils:
    stage: compile
    script:
        - cd GpsUtil
        - gradle compileJava assemble

compile-Rewards:
    stage: compile
    script:
        - cd Rewards
        - gradle compileJava assemble

compile-Pricer:
    stage: compile
    script:
        - cd TripPricer
        - gradle compileJava assemble

############ build ##############
build-TourGuide:
    tags:
        - docker
    stage: build
    script:
        - cd TourGuideApp
        - gradle --build-cache assemble
    artifacts:
        paths:
            - ./TourGuideApp/build/libs/*.jar

build-GpsUtils:
    tags:
        - docker
    stage: build
    script:
        - cd GpsUtil
        - gradle --build-cache assemble
    artifacts:
        paths:
            - ./GpsUtil/build/libs/*.jar

build-Rewards:
    tags:
        - docker
    stage: build
    script:
        - cd Rewards
        - gradle --build-cache assemble
    artifacts:
        paths:
            - ./Rewards/build/libs/*.jar

build-Pricer:
    tags:
        - docker
    stage: build
    script:
        - cd TripPricer
        - gradle --build-cache assemble
    artifacts:
        paths:
            - ./TripPricer/build/libs/*.jar

############ test ##############
test:
    tags:
        - docker
    stage: test
    services:
        -   name: docker:dind
    needs:
        -   job: build-GpsUtils
        -   job: build-Rewards
        -   job: build-Pricer
        -   job: build-TourGuide
    script:
        - cd TourGuideApp
        - gradle clean test --tests 'tourGuide.Unit*'

############ build docker image ##############
build_docker_images:
    tags:
        - docker
    services:
        -   name: docker:dind
    image:
        name: docker/compose:latest
    stage: build_docker_images
    needs:
        -   job: build-GpsUtils
        -   job: build-Rewards
        -   job: build-Pricer
        -   job: build-TourGuide
    script:
        - docker-compose build