version: "3.3"

services:
    gps-util:
        build: ./GpsUtil/.
        image: gps-util:2.0
        container_name: gps-util
        ports:
            - "8081:8081"
    rewards:
        build: ./Rewards/.
        image: rewards:2.0
        container_name: rewards
        ports:
            - "8082:8082"
    tripe-pricer:
        build: ./TripPricer/.
        image: tripe-pricer:2.0
        container_name: tripe-pricer
        ports:
            - "8083:8083"

    tourGuideApp:
        build: ./TourGuideApp/.
        image: tour-guide-app:2.0
        container_name: tour-guide-app
        ports:
            - "8080:8080"
        depends_on:
            - gps-util
            - rewards
            - tripe-pricer
        environment:
            GPS_URL: gps-util:8081
            REWARDS-URL: rewards:8082
            RRICER-URL:  tripe-pricer:8083


